# Exploratory Text Analysis

## What kinds of text analysis are there?

* analyst knows the pattern
    * regular expressions
* analyst does not know the pattern
    * natural language processing
        * compares historical examples to judge novel cases
            * comparisons are statistical and approximate

In [ ]:
# [a-zA-Z]{3}[ ]?[0-9]{4} -> 3 letters of any case, followed by 1 space (optional), followed by 4 nums!
# ?      means 0 or 1 occurance
# +      means 1 or more occurance
# *      means 0 or more occurance
# ^      means start of the pattern
# $      means end of the pattern

### Examples of Analysis

When you know the pattern:

In [ ]:
pattern = '£ ?[0-9][0-9]?' # £ then SPACE-optional then digit then digit-optional

document = 'My eggs cost £ 3, bread cost £2, vodka cost £ 35'

In [ ]:
import re

In [ ]:
re.findall(pattern, document)

['£ 3', '£2', '£ 35']

If you dont:

* sentiment analysis
    * how positive/negative is this (new) review?
* topic analysis
    * what is this document about?

## What can I do if I know what pattern I want to find?

* finding ("extracting")
    * what matches the pattern?
* matching ("validating")
    * does the entire document match YES/NO?
* substitue ("replacing")
    * replace a part that matches a pattern with another...

## How do I validate text with pandas?

In [ ]:
import pandas as pd

In [168]:
ti = pd.read_csv('https://raw.githubusercontent.com/a-forty-two/diamler_17_jan/main/titanic.csv')
ti.sample(2)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
846,0,3,male,NaN,8,2,69.55,S,Third,man,True,NaN,Southampton,no,False
724,1,1,male,27.0,1,0,53.10,S,First,man,True,E,Southampton,yes,False

In [169]:
ti['ticket'] = "Ticket: " + ti['class'] + "; Price: $ " + ti['fare'].astype(str) + "; Port: " + ti['embark_town'] + ";"

In [ ]:
ti[['class', 'fare', 'embark_town', 'ticket']].head(3)

,class,fare,embark_town,ticket
0,Third,7.2500,Southampton,Ticket: Third; Price: $ 7.25; Port: Southampton;
1,First,71.2833,Cherbourg,Ticket: First; Price: $ 71.2833; Port: Cherbourg;
2,Third,7.9250,Southampton,Ticket: Third; Price: $ 7.925; Port: Southampton;

In [ ]:
pattern = '(First|Second)'

ti['class'].str.match(pattern)

0      False
1       True
2      False
3       True
4      False
       ...
886     True
887     True
888    False
889     True
890    False
Name: class, Length: 891, dtype: bool

In [ ]:
ti.loc[ ti['class'].str.match(pattern)  , 'survived'].mean()

0.5575

In [ ]:
pattern = '(Third)'
ti.loc[ ti['class'].str.match(pattern)  , 'survived'].mean()

0.24236252545824846

## How do I extract data with pandas?

In [ ]:
ti[['class', 'fare', 'embark_town', 'ticket']].head(3)

   class  ...                                             ticket
0  Third  ...   Ticket: Third; Price: $ 7.25; Port: Southampton;
1  First  ...  Ticket: First; Price: $ 71.2833; Port: Cherbourg;
2  Third  ...  Ticket: Third; Price: $ 7.925; Port: Southampton;

[3 rows x 4 columns]

In [ ]:
#just for demo, no real purpose
pattern = '([0-9.]+)'

ti['ticket'].str.extract(pattern).sample(4)

           0
848     33.0
869  11.1333
405     21.0
651     23.0

## How do I substitue text with pandas?

In [ ]:
ti['ticket'].str.replace('$', '€').sample(1)

430    Ticket: First; Price: € 26.55; Port: Southampton;
Name: ticket, dtype: object

## What are regular expressions?

Regular expressions are a language for describing patterns in text.

They are separate from python, but may be used within python program. (And elsewhere, eg., often in SQL).

They are notoriously difficult to read and write; and as a separate language, an additional tool to learn.

## What regular expression patterns can I use?

* literals
    * `a`, find me an `a`
    * `£`, find `£`
    * `!` means `!`
    * ... most symbols mean "find me"
* `.`
    * find any **single** symbol
* character classes -- find a **single** symbol
    * `[abc]` $\rightarrow$ **either** a, b, c
    * `[0-9]` $\rightarrow$ **either** 0, 1, 2, 3,...9
    * `[A-Z]` $\rightarrow$ **either** capital A, B, ... Z
    * inversions
        * `[^abc]` $\rightarrow$ **is not** `a` OR `b` OR `c`
        * `[^a-zA-Z0-9 ]`  $\rightarrow$ **is not** alphanumeric-ish
    
* alternatives -- find the character**s** given by...
    * `(May|June|July)`  $\rightarrow$ **the whole worlds** May OR June..

In [ ]:
ti['ticket'].str.extract('(Ticket: (First|Second))')

In [ ]:
ti['ticket'].str.extract('( [0-9][0-9])')

In [ ]:
ti['ticket'].sample(1)

In [ ]:
ti['ticket'].str.extract('(Ticket: [A-Z])').sample(2)

In [ ]:
ti['ticket'].str.extract('(T........)').sample(3)

In [ ]:
ti['ticket'].str.extract('(Price: [^0-9A-Za-z] ..)').sample(3)

In [ ]:
ti['ticket'].str.extract('(Port: (Cherbourg|Southampton))').sample(3)

* repetitions
    * optional `?`
        * an optional number: `[0-9]?`
    * one or more `+`
        * one or more spaces: ` +`  
    * optional, or more, `*`
        * ` [0-9][0-9]?.[0-9]*`

In [ ]:
ti['ticket'].str.extract('([0-9][0-9]?.[0-9]*)').sample(3)

In [ ]:
ti['ticket'].str.extract('(Ticket: [a-zA-Z]+)').sample(3)

In [ ]:
row = 0
match = 1 # second match

ti['ticket'].str.extractall('([a-zA-Z]+: [a-zA-Z]+)').loc[row, match]

In [ ]:
ti['ticket'].str.extract('([a-zA-Z]+tow?n)')

* EXTRA:
    * escaping
        * How do I say, literally, the `.` symbol?
        * `\.`

In [ ]:
ti['ticket'].str.extract('(\$ [0-9]+\.[0-9]+)').sample(2)

* positional matching
    * `^` means **at the beginning**
    * `$` means **at the end**

In [ ]:
ti['ticket'].str.extractall('([a-zA-Z]+: [a-zA-Z]+;$)').sample(1)

In [ ]:
ti['ticket'].str.extractall('(^[a-zA-Z]+: [a-zA-Z]+;)').sample(1)

                      0
  match
2 0      Ticket: Third;

## Next Steps

* review a "Regex Cheat Sheet"
    * also, eg., https://en.wikipedia.org/wiki/Regular_expression#Examples

## Exercise (30 min)

* find all the words in the tickets
    * HINT: a word is a repeated letter followed by a space or a colon
    * HINT: `[ :]` means a space or a colon
* find all the USD prices
    * HINT: ``` \$ ``` and repeated numbers
    
* find all the high-price tickets
    * HINT: consider `\$`, tripple-digit number, `\.`

In [171]:
#Solution
ti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,ticket
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Ticket: Third; Price: $ 7.25; Port: Southampton;
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Ticket: First; Price: $ 71.2833; Port: Cherbourg;
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Ticket: Third; Price: $ 7.925; Port: Southampton;
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Ticket: First; Price: $ 53.1; Port: Southampton;
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Ticket: Third; Price: $ 8.05; Port: Southampton;

In [170]:
ti['ticket'].str.findall('([a-zA-Z]+[ :])')

0      [Ticket:, Price:, Port:]
1      [Ticket:, Price:, Port:]
2      [Ticket:, Price:, Port:]
3      [Ticket:, Price:, Port:]
4      [Ticket:, Price:, Port:]
                 ...
886    [Ticket:, Price:, Port:]
887    [Ticket:, Price:, Port:]
888    [Ticket:, Price:, Port:]
889    [Ticket:, Price:, Port:]
890    [Ticket:, Price:, Port:]
Name: ticket, Length: 891, dtype: object

In [172]:
ticket_word_list= list(ti['ticket'].str.findall('([a-zA-Z]+[ :])').dropna())

print(ticket_word_list)

[['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'], ['Ticket:', 'Price:', 'Port:'],

In [173]:
wordset=set(ticket_word_list[0])

In [174]:
import re
words=[]
for word in wordset:
    word=re.findall("[a-zA-Z]+", word)
    # words.append("".join(word))
    words.append(word[0])
print(words)

['Port', 'Ticket', 'Price']

In [178]:
ti['ticket'].str.extract('(\$ [0-9]+\.[0-9]+)')

             0
0       $ 7.25
1    $ 71.2833
2      $ 7.925
3       $ 53.1
4       $ 8.05
..         ...
886     $ 13.0
887     $ 30.0
888    $ 23.45
889     $ 30.0
890     $ 7.75

[891 rows x 1 columns]

In [179]:
ti['price']=ti['ticket'].str.extract('(\$ [0-9]+\.[0-9]+)').replace('\$ ',"",regex=True).astype('float')

In [183]:
# ti['price']=ti['price'].str.replace('\$ ',"",regex=True).astype('float')

ti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,ticket,price
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,Ticket: Third; Price: $ 7.25; Port: Southampton;,7.2500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,Ticket: First; Price: $ 71.2833; Port: Cherbourg;,71.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,Ticket: Third; Price: $ 7.925; Port: Southampton;,7.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,Ticket: First; Price: $ 53.1; Port: Southampton;,53.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,Ticket: Third; Price: $ 8.05; Port: Southampton;,8.0500

In [180]:
ti['price'].max()

512.3292

In [166]:
ti.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,ticket,price
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,$ 7.25,7.2500
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,$ 71.2833,71.2833
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,$ 7.925,7.9250
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,$ 53.1,53.1000
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,$ 8.05,8.0500

In [185]:
row = 0
match = 1 # second match
# ti['ticket'].str.extractall('(\$ [0-9][0-9][0-9]+\.[0-9]+)')#.loc[row, 0]

ti.sort_values(by="price",ascending=False)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,ticket,price
258,1,1,female,35.0,0,0,512.3292,C,First,woman,False,NaN,Cherbourg,yes,True,Ticket: First; Price: $ 512.3292; Port: Cherbo...,512.3292
737,1,1,male,35.0,0,0,512.3292,C,First,man,True,B,Cherbourg,yes,True,Ticket: First; Price: $ 512.3292; Port: Cherbo...,512.3292
679,1,1,male,36.0,0,1,512.3292,C,First,man,True,B,Cherbourg,yes,False,Ticket: First; Price: $ 512.3292; Port: Cherbo...,512.3292
341,1,1,female,24.0,3,2,263.0000,S,First,woman,False,C,Southampton,yes,False,Ticket: First; Price: $ 263.0; Port: Southampton;,263.0000
27,0,1,male,19.0,3,2,263.0000,S,First,man,True,C,Southampton,no,False,Ticket: First; Price: $ 263.0; Port: Southampton;,263.0000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
806,0,1,male,39.0,0,0,0.0000,S,First,man,True,A,Southampton,no,True,Ticket: First; Price: $ 0.0; Port: Southampton;,0.0000
481,0,2,male,NaN,0,0,0.0000,S,Second,man,True,NaN,Southampton,no,True,Ticket: Second; Price: $ 0.0; Port: Southampton;,0.0000
597,0,3,male,49.0,0,0,0.0000,S,Third,man,True,NaN,Southampton,no,True,Ticket: Third; Price: $ 0.0; Port: Southampton;,0.0000
61,1,1,female,38.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True,NaN,NaN
829,1,1,female,62.0,0,0,80.0000,NaN,First,woman,False,B,NaN,yes,True,NaN,NaN

                    0
    match
27  0         $ 263.0
31  0      $ 146.5208
88  0         $ 263.0
118 0      $ 247.5208
195 0      $ 146.5208